[net]
port = 10200
ipv4 = [0,0,0,0]


[db.mongo]
db = "virtuareal"
host = "localhost"
port = 27017


[[room]]
roomid = 23260932
channel = ["json"]

[[room]]
roomid = 5229
channel = ["json"]

[[room]]
roomid = 23805066
channel = ["json", "bincode"]
